
id = "TitlesPatching"
name = "TitlesPatching"
description = "Patches some stuff for TitlesPlus"
version = "1.0.0"
homepage = ""
author = "IamKikin"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./TitlesPatching/TitlesPatching.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"
